# Generated by Django 5.0.6 on 2024-07-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_task_username_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='deadline',
        ),
    ]
